### ISSUE TITLE
Add mausoleum cryptotheology

### ISSUE THREAD

**Issue by hickeys** [oliversalzburg/cbc-kitten-scientists#103]

**Comment by oliversalzburg** [comment]
Any more infos on this? I don't have mausoleums.

**Comment by hickeys** [comment]
I apparently jumped the gun. It's still in beta, but it's showing up for me. The pacts that it mentions do not show up yet.

<img width="289" alt="image" src="https://user-images.githubusercontent.com/8008261/177209639-d3b38e9e-0833-47d6-a773-61370e21ad0e.png">

<img width="307" alt="image" src="https://user-images.githubusercontent.com/8008261/177209732-14faac95-ee5c-4d36-84ba-43819ceeaa89.png">

**Comment by oliversalzburg** [comment]
Oh, interesting. In general, I'm not opposed to supporting beta features, especially if it would just be adding a new entry for a build.

However, beta feature handling is currently not ideal. KS used to have village exploration, then I removed it from the rewrite, because it was no longer in the game, and now exploration is back! :D To properly maintain the state of beta features in the script, I feel that it needs a different level of maturity still.

**Comment by hickeys** [comment]
Yeah, I think I take this one back. When I saw it show up in the religion tab, I assumed it was released. I used a save editor to un-buy it and now it doesn't show up anymore.
