### ISSUE TITLE
Expand/collapse all buttons

### ISSUE THREAD

**Issue by hickeys** [oliversalzburg/cbc-kitten-scientists#109]
Probably these go on the same line as the []Enable Scientists button, but a collapse all button on the bottom (below the []Filters] section would be helpful too

**Comment by oliversalzburg** [comment]
And that should expand/collapse all main settings sections?

**Comment by hickeys** [comment]
Yes, as if you clicked the + button (tooltip: 'Show Options') on all sections.

There are two use cases I'm thinking here:
  (1) I want to change the focus of my run from what I did last time. Maybe last time I focused on void, and so changed a bunch of settings in a bunch of sections. Now I want to focus on paragon, so lots more updates.

  (2) I use sleek theme, which puts the tooltips in the upper right corner of the scientists/log/chat column. If I've forgotten to collapse a few settings panels, I can't see the tooltips. Usually when this happens, I'm scrolled to the bottom of KS/top of the game log, so a collapse button right there would be very helpful.

**Comment by oliversalzburg** [comment]
That sounds very reasonable.

I was also pondering to have different configuration presets. So you could easily switch between different setups, but I don't think that would properly cover what you're describing.

What do you think of Shift+Click on the +/- button to make it toggle all sections? Instead of a dedicated button.

**Comment by hickeys** [comment]
> I was also pondering to have different configuration presets. 

I mentioned this too, but didn't want to get too greedy :)

Shift click doesn't seem discoverable, but it seems like it would work fine once you know about it. I assume you can shift-click on any + or -?

**Comment by oliversalzburg** [comment]
Yeah, Shift+Click on the +/- was the idea. I agree that it's barely discoverable, which I like to avoid, but I also don't like too many controls cluttering up the UI. I just figured because Shift+Click also does things in the game, like buying _all_ available buildings instead of one, I figured it's close enough.

We'll see, maybe one of the +/- buttons on the main "Enable Scientists" section could also work.
