### ISSUE TITLE
Auto-adore always activates

### ISSUE THREAD

**Issue by Fhurries** [oliversalzburg/cbc-kitten-scientists#127]
As of Alpha5 this will continuously adore regardless of current worship leaving you at 0 worship and effectively 0 solar revolution.

**Comment by oliversalzburg** [comment]
Wow, sorry about that. Somehow I didn't even notice this myself.

It's possible that this might already be fixed in my latest code state (which isn't published yet). I'll verify this before alpha.6, which is likely due this week.

**Comment by oliversalzburg** [comment]
I didn't notice this myself, because I have the feature disabled. I remember I looked at the code a while ago and could not make sense of it. The values played out so that it was still far away from my trigger value. So I figured I delay working on it.

Can you share your game save where this happens, so that I can debug the behavior?

**Comment by Fhurries** [comment]
[Kittens Game.txt](https://github.com/oliversalzburg/cbc-kitten-scientists/files/9766425/Kittens.Game.txt)

**Comment by Fhurries** [comment]
Just incase, figured I'd take a few screenshots of before and after enabling. Value is set to default .750:
![image](https://user-images.githubusercontent.com/114759421/195384579-fcafc8d0-047b-41b3-9818-8491445b908b.png)
![image](https://user-images.githubusercontent.com/114759421/195384780-54b8d37b-a03b-47e7-a240-ea39e94103cc.png)

**Comment by Fhurries** [comment]
Previously (here and in the original script) it seemed to only adore when two conditions were met at the same time: you had max faith & you would reach trigger % of your capped solar revolution. At the point I am at it should effectively adore before every praise. Those earlier in the game would go many praises before it adores/praises.
We can already see that with one praise I can get beyond 75% of my solar revolution cap so the only issue is that it is not waiting for max faith - or perhaps the trigger % for auto-praising.
I think the use case for this is that if you are indeed automating most the game and want it to transcend at the best possible moment and not just at the end of a run. Since this will constantly convert worship, you'll accumulate it until you hit that threshold and triggers auto-transcend.

**Comment by oliversalzburg** [comment]
Thank you. That helped.

I think the different trigger values got a little mixed up and the trigger for the entire section was previously also taken into account. I believe I found a simpler approach that only uses the auto-praise trigger as the ground truth.

This should be fixed in the next build.
